### ISSUE TITLE
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/content/Yolov5-distillation-train-inference/models/common.py'>

### ISSUE THREAD

**Issue by koushikII** [Sharpiless/Yolov5-distillation-train-inference#6]
how to fix this ? plz help 

Traceback (most recent call last):
  File "train_distill.py", line 602, in <module>
    train(hyp, opt, device, tb_writer)
  File "train_distill.py", line 71, in train
    '.pt') and os.path.isfile(weights) else None
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/content/Yolov5-distillation-train-inference/models/common.py'>

**Comment by verages** [comment]
The author is using the 5.0 code. If you want to use SPPF, you need to add SPPF to common.py, and then try to replace the model, instead of directly using the model provided by the author

**Comment by verages** [comment]
> 

The author is using the 5.0 code. If you want to use SPPF, you need to add SPPF to common.py, and then try to replace the model, instead of directly using the model provided by the author

**Comment by verages** [comment]
> how to fix this ? plz help
> 
> Traceback (most recent call last): File "train_distill.py", line 602, in train(hyp, opt, device, tb_writer) File "train_distill.py", line 71, in train '.pt') and os.path.isfile(weights) else None File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 607, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 882, in _load result = unpickler.load() File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 875, in find_class return super().find_class(mod_name, name) AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/content/Yolov5-distillation-train-inference/models/common.py'>

The author is using the 5.0 code. If you want to use SPPF, you need to add SPPF to common.py, and then try to replace the model, instead of directly using the model provided by the author
